# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7288bd9a0ae0f9d08a772929b406c2fdf498b0983810253c7bb5e2f8e894c35f8d004c70e511886ca33b7df94b30df3d5bc1ba37f6dde9ef63225c5c1d3a8dcd

test:
  secret_key_base: 3119eadd1966abf77e1e9700f97de591b9ce874686db35716750208069634eb1b57dfe154b55d28da31a7e0b6863dc88d6b2dab7cd58aefe3fcf8904e51920a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
